name: Trigger workflow via GitHub App token

on:
  workflow_dispatch:  # manually triggered; change to push/schedule if needed

jobs:
  trigger-next:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub App Token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_APP_ID }}          # exact input name: app-id
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Fetch last Git tag
        id: get_tag
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0)
          STRIPPED_TAG=${LAST_TAG#v}
          echo "last_tag=$STRIPPED_TAG" >> $GITHUB_OUTPUT

      - name: Trigger second workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/second.yml/dispatches \
            -d '{"ref":"main","inputs":{"tag":"${{ steps.get_tag.outputs.last_tag }}"}}'
